laravel/first/routes/web.php
<?php



/*

|--------------------------------------------------------------------------

| Web Routes

|--------------------------------------------------------------------------

|

| Here is where you can register web routes for your application. These

| routes are loaded by the RouteServiceProvider within a group which

| contains the "web" middleware group. Now create something great!

|

*/



Route::get('/', function () {

    return view('welcome');

});





Route::get('/admin-panel', function () {

   return view('admin.dashboard');

});



Route::resource('/admin-panel/account', 'admin\AcccountController');
Route::post('/admin-panel/account/{id}', 'admin\AcccountController@update');
Route::post('/admin-panel/account/status/{id}', 'admin\AcccountController@status');


Route::get('/admin-login', 'admin\HomeController@index');
// route to process the form
Route::post('/admin-login', 'admin\HomeController@doLogin');



Route::resource('/admin-panel/license', 'admin\LicenseController');

laravel/first/app/Account.php
<?php



namespace App;



use Illuminate\Notifications\Notifiable;

use Illuminate\Foundation\Auth\User as Authenticatable;



class Account extends Authenticatable

{

    use Notifiable;



    /**

     * The attributes that are mass assignable.

     *

     * @var array

     */

    protected $fillable = [

        'name', 'userid', 'contact', 'subdomain', 'key', 'username', 'address',

    ];



    /**

     * The attributes that should be hidden for arrays.

     *

     * @var array

     */

    protected $hidden = [

        'password', 'remember_token',

    ];

}

laravel/first/resources/views/admin/account/create.blade.php
@include('admin.parts.header')

  <!-- Left side column. contains the logo and sidebar -->

  @include('admin.parts.sidebar')


	<?php
	$string = str_random(15);
	
	// Available alpha caracters
$characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

// generate a pin based on 2 * 7 digits + a random character
$pin = mt_rand(10000000, 99999999)
    . mt_rand(1000000, 9999999)
    . $characters[rand(0, strlen($characters) - 1)];

// shuffle the result
$string = str_shuffle($pin);
	
	?>




  <!-- Content Wrapper. Contains page content -->

  <div class="content-wrapper">

    <!-- Content Header (Page header) -->

    <section class="content-header">

      <h1>

        

        <small></small>

      </h1>

      <ol class="breadcrumb">

        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>

        <li><a href="#">Account</a></li>

        <li class="active">Add Account</li>

      </ol>

    </section>



    <!-- Main content -->

    

    <!-- /.content -->

	<section class="content">

      <div class="row">

        <!-- left column -->

        

        <div class="col-md-12">

          <!-- general form elements -->

          <div class="box box-primary">

            <div class="box-header with-border">

              <h3 class="box-title">Add Account</h3>

            </div>


@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
            <!-- /.box-header -->

            <!-- form start -->

            <form role="form" method="post" action="{{ route('account.store') }}" enctype="multipart/form-data">

              <div class="box-body">

                <div class="form-group">

                  <label for="exampleInputEmail1">Name</label>

                  <input type="text" class="form-control" id="name" name="name" value="{{ old('name') }}" placeholder="Name">

				   {{ csrf_field() }}

                </div>

                

				<div class="form-group">

				<label for="exampleInputEmail1">E-Mail</label>

                  <input type="text" class="form-control" id="email" name="email" value="{{ old('email') }}" placeholder="E-Mail">

                </div>



				<div class="form-group">

				<label for="exampleInputEmail1">Contact Number</label>

                  <input type="text" class="form-control" id="contact" name="contact" value="{{ old('contact') }}" placeholder="Contact Number">

                </div>
				
				<div class="form-group">

				<label for="exampleInputEmail1">Sub-Domain</label>

                  <input type="text" class="form-control" id="subdomain" name="subdomain" value="{{ old('subdomain') }}" placeholder="Sub-Domain">

                </div>



				<div class="form-group">

				<label for="exampleInputEmail1">License Keys</label>

                  <input type="text" class="form-control" id="licensekey" name="licensekey" value="<?php echo $string; ?>" placeholder="License Keys">

                </div>

				

				<div class="form-group">

				<label for="exampleInputEmail1">Username</label>

                  <input type="text" class="form-control" id="username" value="{{ old('username') }}"  name="username" placeholder="Username">

                </div>

				<div class="form-group">

				<label for="exampleInputEmail1">Password</label>

                  <input type="text" class="form-control" id="password" value="{{ old('password') }}" name="password" placeholder="Password">

                </div>





                <!--<div class="form-group">

                  <label for="exampleInputFile">File input</label>

                  <input type="file" name="image" id="exampleInputFile">



                  </div>-->

				

				<div class="box-body pad">

              <label for="exampleInputEmail1">Address</label>

                    <textarea id="editor1" name="address" rows="10" cols="20" style="visibility: hidden; display: none;"></textarea>

              

            </div>

                

              </div>

              <!-- /.box-body -->



              <div class="box-footer">

                <button type="submit" class="btn btn-primary">Submit</button>

              </div>

            </form>

          </div>



        </div>

		

        <!--/.col (right) -->

      </div>

      <!-- /.row -->

    </section>

  </div>

  <!-- /.content-wrapper -->

  @include('admin.parts.footer')

laravel/first/resources/views/admin/account/editaccount.blade.php
@include('admin.parts.header')
<!-- Left side column. contains the logo and sidebar -->
@include('admin.parts.sidebar')
<?php
	$string = str_random(15);
	
	// Available alpha caracters
$characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

// generate a pin based on 2 * 7 digits + a random character
$pin = mt_rand(10000000, 99999999)
    . mt_rand(1000000, 9999999)
    . $characters[rand(0, strlen($characters) - 1)];

// shuffle the result
$string = str_shuffle($pin);
	
	?>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1> <small></small> </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="#">Account</a></li>
      <li class="active">Add Account</li>
    </ol>
  </section>
  <!-- Main content -->
  <!-- /.content -->
  <section class="content">
    <div class="row">
      <!-- left column -->
      <div class="col-md-12">
        <!-- general form elements -->
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Add Account</h3>
          </div>
          @if ($errors->any())
          <div class="alert alert-danger">
            <ul>
              @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
              @endforeach
            </ul>
          </div>
          @endif
          <!-- /.box-header -->
          <!-- form start -->
          @foreach ($user as $key => $user1)
          <?php if($account->userid == $user1->id){?>
          <form role="form" method="post" action="{{ route('account.update',$user1->id) }}" enctype="multipart/form-data">
            <?php } ?>
            @endforeach
            <div class="box-body">
              <div class="form-group">
                <label for="exampleInputEmail1">Name</label>
                <input type="text" class="form-control" id="name" name="name" value="{{$account->name}}" placeholder="Name">
                {{ csrf_field() }} </div>
              <div class="form-group">
                <label for="exampleInputEmail1">E-Mail</label>
                @foreach ($user as $key => $user1)
                <?php if($account->userid == $user1->id){?>
                <input type="text" class="form-control" id="email" name="email" value="{{$user1->email}}" placeholder="E-Mail">
                <?php }  ?>
                @endforeach </div>
              <input name="updateid" type="hidden" value="{{$account->userid}}">
              <div class="form-group">
                <label for="exampleInputEmail1">Contact Number</label>
                <input type="text" class="form-control" id="contact" name="contact" value="{{$account->contact}}" placeholder="Contact Number">
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Sub-Domain</label>
                <input type="text" class="form-control" id="subdomain" name="subdomain" value="{{$account->subdomain}}" placeholder="Sub-Domain">
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">License Keys</label>
                <input type="text" class="form-control" id="licensekey" name="licensekey" value="{{$account->licensekey}}" placeholder="License Keys">
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Username</label>
                <input type="text" class="form-control" id="username" value="{{$account->username}}"  name="username" placeholder="Username">
              </div>
              <!--<div class="form-group">
                <label for="exampleInputEmail1">Password</label>
                @foreach ($user as $key => $user1)
                <?php //if($account->userid == $user1->id){?>
                <input type="text" class="form-control" id="password" value="{{$user1->password}}" name="password" placeholder="Password">
                <?php //}  ?>
                @endforeach </div>-->
              <!--<div class="form-group">

                  <label for="exampleInputFile">File input</label>

                  <input type="file" name="image" id="exampleInputFile">



                  </div>-->
              <input type="hidden" class="form-control" id="status" value="{{$account->status}}"  name="status" placeholder="Username">
              <div class="box-body pad">
                <label for="exampleInputEmail1">Address</label>
                <textarea id="editor1" name="address" rows="10" cols="20" style="visibility: hidden; display: none;">{{$account->address}}</textarea>
              </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
              <button type="submit" class="btn btn-primary">Update</button>
            </div>
          </form>
        </div>
      </div>
      <!--/.col (right) -->
    </div>
    <!-- /.row -->
  </section>
</div>
<!-- /.content-wrapper -->
@include('admin.parts.footer') 

laravel/first/resources/views/admin/account/index.blade.php
@include('admin.parts.header')

<!-- Left side column. contains the logo and sidebar -->

@include('admin.parts.sidebar')

<!-- Content Wrapper. Contains page content -->

  <div class="content-wrapper">

    <!-- Content Header (Page header) -->

    <section class="content-header">

      <h1>

        Account Tables

        <small>advanced tables</small>

      </h1>

      

    </section>



    <!-- Main content -->

    <section class="content">

      <div class="row">

        <div class="col-xs-12">

          

		  

          <!-- /.box -->

@if (session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
@endif

          <div class="box">

            <div class="box-header">

              <h3 class="box-title">Account List</h3>

            </div>

			<a href="{{ route('account.create') }}"><button type="button" class="btn btn-block btn-primary btn-lg">Add Account</button></a>

            <!-- /.box-header -->

            <div class="box-body">

              <table id="example1" class="table table-bordered table-striped">

                <thead>

                <tr>

                  <th>ID</th>

                  <th>Name</th>

				  <th>Email</th>

				 <th>Username</th>
				  

				  <th>Sub-Domain</th>

				  <th width="280px">Action</th>

                </tr>

                </thead>

				

                <tbody>
								<?php $i=0; ?>
		 @foreach ($account as $key => $account1)

                <tr>
                  <td>{{ ++$i }}</td>
                  <td>{{ $account1->name }}</td>
				  <td>@foreach ($user as $key => $user1)
                  <?php if($account1->userid == $user1->id){echo $user1->email;}
				  ?>
					@endforeach
					</td>
                  <td>{{ $account1->username }}</td>
                  <td>{{ $account1->subdomain }}</td>
				  <td>
				  <a href="{{ route('account.edit',$account1->id) }}"><button type="button" class="btn btn-block btn-info">Edit</button></a>
				 <form method="post" action="{{ route('account.destroy',$account1->userid) }}" accept-charset="UTF-8" style="display:inline">
				  <input name="deleteid" type="hidden" value="{{$account1->userid}}">
				  <input name="_method" type="hidden" value="DELETE">
				  {{ csrf_field() }}
				  <button type="submit" class="btn btn-block btn-danger">Delete</button>
				  </form>
				  
				  
				  <?php if($account1->status == 0){?>
				  <form method="post" action="{{ URL::to('admin-panel/account/status',$account1->id) }}" accept-charset="UTF-8" style="display:inline">
				  <input name="statusid" type="hidden" value="1">
				  
				  {{ csrf_field() }}
				  <button type="submit" class="btn btn-block btn-success" data-toggle=confirmation>Active</button>
				  </form>
				  <?php } else {?>
				  <form method="post" action="{{ URL::to('admin-panel/account/status',$account1->id) }}" accept-charset="UTF-8" style="display:inline">
				  <input name="statusid" type="hidden" value="0">
				 
				  {{ csrf_field() }}
				  <button type="submit" class="btn btn-block btn-danger">Deactive</button>
				  </form>
				  <?php } ?>
				  </td>
                </tr>
			@endforeach

                </tfoot>

              </table>

            </div>



			<script type="text/javascript">
				$(document).ready(function () {        
					$('[data-toggle=confirmation]').confirmation({
						rootSelector: '[data-toggle=confirmation]',
						onConfirm: function (event, element) {
							element.closest('form').submit();
						}
					});   
				});
			</script>
            <!-- /.box-body -->

          </div>

          <!-- /.box -->

        </div>

        <!-- /.col -->

      </div>

      <!-- /.row -->

    </section>

    <!-- /.content -->

  </div>

  <!-- /.content-wrapper -->

  @include('admin.parts.footer')