laravel/first/routes/web.php
<?php



/*

|--------------------------------------------------------------------------

| Web Routes

|--------------------------------------------------------------------------

|

| Here is where you can register web routes for your application. These

| routes are loaded by the RouteServiceProvider within a group which

| contains the "web" middleware group. Now create something great!

|

*/



Route::get('/', function () {

    return view('welcome');

});





Route::get('/admin-panel', function () {

   return view('admin.dashboard');

});



Route::resource('/admin-panel/account', 'admin\AcccountController');
Route::post('/admin-panel/account/{id}', 'admin\AcccountController@update');
Route::post('/admin-panel/account/status/{id}', 'admin\AcccountController@status');


Route::get('/admin-login', 'admin\HomeController@index');
// route to process the form
Route::post('/admin-login', 'admin\HomeController@doLogin');



Route::resource('/admin-panel/license', 'admin\LicenseController');

laravel/first/app/License.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class License extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'userid', 'years',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

laravel/first/app/Http/Controllers/admin/LicenseController.php
<?php



namespace App\Http\Controllers\Admin;



use App\Http\Controllers\Controller;
use Hash;
use Redirect;

use Schema;

use App\Account;
use App\User;

use App\License;


use App\Http\Requests\CreateProductRequest;

use App\Http\Requests\UpdateProductRequest;

use Illuminate\Http\Request;

use App\Http\Controllers\Traits\FileUploadTrait;

use Illuminate\Foundation\Validation\ValidatesRequests;



class LicenseController extends Controller

{

	use ValidatesRequests;

	public function index()

    {

        
		$account = Account::orderBy('id','DESC')->get();
		$license = License::orderBy('id','DESC')->get();
		return view('admin.license.index',compact('account','license'));

	}

	public function create()

	{
		$account = Account::orderBy('id','DESC')->get();
	    return view('admin.license.create',compact('account'));
	}


	public function store(Request $request)

	{
	
		$request->validate([
		'years' => 'required|min:1|max:99|numeric',
	]);

		$license = new License($request->input()) ;
        $license->save() ;

		return redirect()->route('license.index')->with('message', 'License Year added Successfully');;

	}

	public function destroy($id)
    {
        License::find($id)->delete();
        return redirect()->route('license.index');
    }

	 public function edit($id)
    {
        $license = License::find($id);
		$account = Account::orderBy('id','DESC')->get();
        return view('admin.license.editlicense',compact('account','license'));
    }



	public function update(Request $request, $id)
    {
		$request->validate([
		'years' => 'required|min:1|max:99|numeric',
	]);
	  $license = License::find($id);
      // replace old data with new data from the submitted form //
      $license->userid = $request->input('username');
      $license->years = $request->input('years');
      $license->save();
	  //Category::find($id)->update($request->all());
	   return redirect()->route('license.index');
    }


}

laravel/first/resources/views/admin/license/create.blade.php
@include('admin.parts.header')
  <!-- Left side column. contains the logo and sidebar -->
  @include('admin.parts.sidebar')


  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        
        <small></small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">License</a></li>
        <li class="active">Add License</li>
      </ol>
    </section>

    <!-- Main content -->
    
    <!-- /.content -->
	<section class="content">
      <div class="row">
        <!-- left column -->
        
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Add License</h3>
            </div>
            <!-- /.box-header -->
			
			@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

			
            <!-- form start -->
            <form role="form" method="post" action="{{ route('license.store') }}" enctype="multipart/form-data">
              <div class="box-body">
                
                
				<div class="form-group">
                  <label>Select Username</label>
                  <select class="form-control" name="userid">
				   @foreach ($account as $key => $account1)
                    <option value="{{ $account1->id }}">{{ $account1->name }}</option>
					@endforeach
                  </select>
                </div>


				

				<div class="form-group">
				<label for="exampleInputEmail1">Year</label>
                  <input type="text" class="form-control" id="year" name="years" placeholder="Year">
				  {{ csrf_field() }}
                </div>
				
				
				
                
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>

        </div>
		
        <!--/.col (right) -->
      </div>
      <!-- /.row -->
    </section>
  </div>
  <!-- /.content-wrapper -->
  @include('admin.parts.footer')

laravel/first/resources/views/admin/license/editlicense.blade.php
@include('admin.parts.header')
  <!-- Left side column. contains the logo and sidebar -->
  @include('admin.parts.sidebar')


  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Edit License
        <small></small>
      </h1>
      
    </section>

    <!-- Main content -->
    
    <!-- /.content -->
	<section class="content">
      <div class="row">
        <!-- left column -->
        
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Edit License</h3>
            </div>
            <!-- /.box-header -->
			
			@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
			
			
            <!-- form start -->
            <form role="form" method="post" action="{{ route('license.update',$license->id) }}" enctype="multipart/form-data">
              <div class="box-body">
                
                
				<div class="form-group">
                  <label>Select</label>
                  <select class="form-control" name="username">
				   @foreach ($account as $key => $account1)
                    <option value="{{ $account1->id }}" {{ $license->userid == $account1->id ? 'selected' : '' }}>{{ $account1->name }}</option>
					@endforeach
                  </select>
                </div>
				
				<div class="form-group">

                  <label for="exampleInputEmail1">Year</label>
				  <input type="text" class="form-control" id="years" name="years" value="{{$license->years}}" placeholder="Year">
                  <input name="_method" type="hidden" value="PATCH">
				 {{ csrf_field() }}
                </div>
                
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Update</button>
              </div>
            </form>
          </div>

        </div>
		
        <!--/.col (right) -->
      </div>
      <!-- /.row -->
    </section>
  </div>
  <!-- /.content-wrapper -->
  @include('admin.parts.footer')

laravel/first/resources/views/admin/license/index.blade.php
@include('admin.parts.header')
<!-- Left side column. contains the logo and sidebar -->
@include('admin.parts.sidebar')
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        
        <small></small>
      </h1>
      <ol class="breadcrumb">
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          
		  
          <!-- /.box -->

          <div class="box">
            <div class="box-header">
              <h3 class="box-title">License List</h3>
            </div>
			<a href="{{ route('license.create') }}"><button type="button" class="btn btn-block btn-primary btn-lg">Add License</button></a>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>ID</th>
                  <th>Username</th>
				  <th>Year</th>
				  
				  <th width="280px">Action</th>
                </tr>
                </thead>
				
                <tbody>
				<?php $i=0; ?>
		 @foreach ($license as $key => $license1)

                  <td>{{ ++$i }}</td>
                  <td>@foreach ($account as $key => $account1)
                  <?php if($account1->id == $license1->userid){echo $account1->username;}
				  ?>
					@endforeach</td>
                  <td>{{ $license1->years }}</td>
				  <td>
				  <a href="{{ route('license.edit',$license1->id) }}"><button type="button" class="btn btn-block btn-info">Edit</button></a>
				 <form method="post" action="{{ route('license.destroy',$license1->id) }}" accept-charset="UTF-8" style="display:inline">
				  <input name="_method" type="hidden" value="DELETE">
				  {{ csrf_field() }}
				  <button type="submit" class="btn btn-block btn-danger">Delete</button>
				  </form>
				  </td>
                </tr>
				@endforeach
                </tfoot>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  @include('admin.parts.footer')